export const Login = {
  USER_LOGIN: 'USER_LOGIN',
  USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
  USER_LOGIN_FAILURE: 'USER_LOGIN_FAILURE',
  USER_LOGOUT: 'USER_LOGOUT',
}

export const Bookmark = {
  GET_BOOKMARK: 'GET_BOOKMARK',
}

export const User = {
  CREATE_NEW_USER: 'CREATE_NEW_USER',
}
