export const Login = {
  LOGIN: 'LOGIN',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  GET: 'GET',
  REQUEST_GET: 'REQUEST_GET',
  LOGOUT: 'LOGOUT',
}

export const Bookmark = {
  ADD: 'ADD',
  GET: 'GET',
  REQUEST_GET: 'REQUEST_GET',
  DELETE: 'DELETE',
  ADD_SUCCESS: 'ADD_SUCCESS',
  DELETE_SUCCESS: 'DELETE_SUCCESS',
}

export const User = {
  CREATE_NEW_USER: 'CREATE_NEW_USER',
  USER_GET: 'USER_GET',
}

export const Toast = {
  SUCCESS: 'SUCCESS',
  ERROR: 'ERROR',
}
