export const Login = {
  SIGN_IN: 'LOGIN_SIGN_IN',
  SIGN_IN_SUCCESS: 'LOGIN_SIGN_IN_SUCCESS',
  SIGN_IN_TOKEN: 'LOGIN_SIGN_IN_TOKEN',
  SIGN_OUT: 'LOGIN_SIGN_OUT',
}

export const Bookmark = {
  ADD: 'BOOKMARK_ADD',
  GET: 'BOOKMARK_GET',
  REQUEST_GET: 'BOOKMARK_REQUEST_GET',
  DELETE: 'BOOKMARK_DELETE',
  ADD_SUCCESS: 'BOOKMARK_ADD_SUCCESS',
  DELETE_SUCCESS: 'BOOKMARK_DELETE_SUCCESS',
}

export const Feed = {
  ADD: 'FEED_ADD',
  GET: 'FEED_GET',
  REQUEST_GET: 'FEED_REQUEST_GET',
  DELETE: 'FEED_DELETE',
  ADD_SUCCESS: 'FEED_ADD_SUCCESS',
  DELETE_SUCCESS: 'FEED_DELETE_SUCCESS',
}

export const User = {
  ADD: 'USER_ADD',
  GET: 'USER_GET',
  UPDATE: 'USER_UPDATE',
}

export const Toast = {
  SUCCESS: 'TOAST_SUCCESS',
  ERROR: 'TOAST_ERROR',
}
